[project]
name = "claude-studies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luiza B. Laquini", email = "luizablaquini@hotmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.121.0",
    "dotenv>=0.9.9",
]

[project.scripts]
claude-studies = "claude_studies:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
